#
# docker-compose -p sr up -d
# docker-compose -p sr down
#
version: '3'

networks:
  sf-net:

services:
  sf-mysql:
    image: "mysql:5.5.51"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=storyfinder
      - MYSQL_USER=storyfinder
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=storyfinder
    volumes:
      - ${PWD}/../mysql-data:/var/lib/mysql
    networks:
      sf-net:
        aliases:
          - mysql

  sf-corenlp:
    image: "kisad/corenlp-german:latest"
    networks:
      sf-net:
        aliases:
          - corenlp

  sf-server-kisad:
    image: "kisad/storyfinder-webserver"
    ports:
      - "3055:3055"
    environment:
      - NODE_ENV=production
      - COOKIE_SECRET=YOUR_COOKIE_SECRET
    restart: unless-stopped
    networks:
      sf-net:
