FROM node:6

RUN DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y --no-install-recommends apt-utils && apt-get install -y libcairo2-dev libjpeg62-turbo-dev libpango1.0-dev libgif-dev build-essential

VOLUME /usr/src/app
WORKDIR /usr/src/app
EXPOSE 3055

# user docker attach and "Ctrl-p + Ctrl-q" in order to gracefully detach or "Ctrl-c" in order to cancel the process
CMD [ "bash" ]
